{
    '_server': <PlexServer:http://192.168.1.100>,
    '_data': <Element 'Video' at 0x7f9f331a1710>,
    '_initpath': '/library/sections/1/all?includeGuids=1&type=1',
    '_parent': <weakref at 0x7f9f334b61b0; to 'MovieSection' at 0x7f9f33473ca0>,
    '_details_key': '/library/metadata/31010?includeBandwidths=1&includeChapters=1&includeFields=thumbBlurHash%2CartBlurHash&includeGeolocation=1&includeLoudnessRamps=1&includeMarkers=1',
    '_overwriteNone': True,
    '_autoReload': True,
    '_edits': None,
    'addedAt': datetime.datetime(2022, 12, 30, 18, 3, 41),
    'art': '/library/metadata/31010/art/1718592061',
    'artBlurHash': None,
    'fields': [],
    'guid': 'plex://movie/5d7768374de0ee001fccc04a',
    'key': '/library/metadata/31010',
    'lastRatedAt': None,
    'lastViewedAt': None,
    'librarySectionID': 1,
    'librarySectionKey': None,
    'librarySectionTitle': None,
    'listType': 'video',
    'ratingKey': 31010,
    'summary': "He's a man of peace in a savage land: Suburbia. When secretive new neighbors move in next door, suburbanite Ray Peterson and his friends let their paranoia get the best of them as they start to suspect the newcomers of evil doings and commence an investigation.But it's hardly how Ray, who much prefers to drink beer, read his newspaper, and watch a ballgame on the tube, expected to spend his vacation.",
    'thumb': '/library/metadata/31010/thumb/1718592061',
    'thumbBlurHash': None,
    'title': "The 'Burbs",
    'titleSort': "'Burbs",
    'type': 'movie',
    'updatedAt': datetime.datetime(2024, 6, 17, 2, 41, 1),
    'userRating': None,
    'viewCount': 0,
    'playlistItemID': None,
    'playQueueItemID': None,
    'audienceRating': 7.1,
    'audienceRatingImage': 'rottentomatoes://image.rating.upright',
    'chapters': [],
    'chapterSource': 'media',
    'collections': [],
    'contentRating': 'PG',
    'countries': [<Country:United-States-of-Ame>],
    'directors': [<Director:Joe-Dante>],
    'duration': 6100386,
    'editionTitle': None,
    'enableCreditsMarkerGeneration': -1,
    'genres': [<Genre:Comedy>, <Genre:Thriller>],
    'guids': [<Guid:imdb://tt0096734>, <Guid:tmdb://11974>, <Guid:tvdb://5869>],
    'labels': [],
    'languageOverride': None,
    'markers': [],
    'media': [<Media:68846>],
    'originallyAvailableAt': datetime.datetime(1988, 11, 30, 0, 0),
    'originalTitle': None,
    'primaryExtraKey': '/library/metadata/39758',
    'producers': [],
    'rating': 5.6,
    'ratingImage': 'rottentomatoes://image.rating.rotten',
    'ratings': [],
    'roles': [<Role:Tom-Hanks>, <Role:Bruce-Dern>, <Role:Carrie-Fisher>],
    'slug': 'the-burbs',
    'similar': [],
    'sourceURI': None,
    'studio': 'Universal Pictures',
    'tagline': "He's a man of peace in a savage land... Suburbia.",
    'theme': None,
    'ultraBlurColors': <UltraBlurColors>,
    'useOriginalTitle': -1,
    'viewOffset': 0,
    'writers': [<Writer:Dana-Olsen>],
    'year': 1988
}
