"""empty message

Revision ID: cb81d7064e71
Revises: f1bcd0286995
Create Date: 2024-09-01 01:16:37.471255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb81d7064e71'
down_revision = 'f1bcd0286995'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('librarySectionID', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sourceURI', sa.String(), nullable=True))
        batch_op.drop_column('librarySectionId')
        batch_op.drop_column('sourceUri')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sourceUri', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('librarySectionId', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('sourceURI')
        batch_op.drop_column('librarySectionID')

    # ### end Alembic commands ###
