"""empty message

Revision ID: f1bcd0286995
Revises: 
Create Date: 2024-09-01 01:03:48.513438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1bcd0286995'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('library',
    sa.Column('identifier', sa.String(), nullable=True),
    sa.Column('mediaTagVersion', sa.String(), nullable=True),
    sa.Column('title1', sa.String(), nullable=True),
    sa.Column('title2', sa.String(), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movie',
    sa.Column('addedAt', sa.DateTime(), nullable=True),
    sa.Column('art', sa.String(), nullable=True),
    sa.Column('artBlurHash', sa.String(), nullable=True),
    sa.Column('guid', sa.String(), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('lastRatedAt', sa.DateTime(), nullable=True),
    sa.Column('lastViewedAt', sa.DateTime(), nullable=True),
    sa.Column('librarySectionId', sa.Integer(), nullable=True),
    sa.Column('librarySectionKey', sa.String(), nullable=True),
    sa.Column('librarySectionTitle', sa.String(), nullable=True),
    sa.Column('listType', sa.String(), nullable=True),
    sa.Column('ratingKey', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('thumb', sa.String(), nullable=True),
    sa.Column('thumbBlurHash', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('titleSort', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('userRating', sa.Float(), nullable=True),
    sa.Column('viewCount', sa.Integer(), nullable=True),
    sa.Column('playlistItemId', sa.Integer(), nullable=True),
    sa.Column('playQueueItemId', sa.Integer(), nullable=True),
    sa.Column('audienceRating', sa.Float(), nullable=True),
    sa.Column('audienceRatingImage', sa.String(), nullable=True),
    sa.Column('chapterSource', sa.String(), nullable=True),
    sa.Column('contentRating', sa.String(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('editionTitle', sa.String(), nullable=True),
    sa.Column('enableCreditsMarkerGeneration', sa.Integer(), nullable=True),
    sa.Column('languageOverride', sa.String(), nullable=True),
    sa.Column('originallyAvailableAt', sa.DateTime(), nullable=True),
    sa.Column('originalTitle', sa.String(), nullable=True),
    sa.Column('primaryExtraKey', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('ratingImage', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('sourceUri', sa.String(), nullable=True),
    sa.Column('studio', sa.String(), nullable=True),
    sa.Column('tagline', sa.String(), nullable=True),
    sa.Column('theme', sa.String(), nullable=True),
    sa.Column('useOriginalTitle', sa.Integer(), nullable=True),
    sa.Column('viewOffset', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('section',
    sa.Column('agent', sa.String(), nullable=True),
    sa.Column('allow_sync', sa.Boolean(), nullable=True),
    sa.Column('art', sa.String(), nullable=True),
    sa.Column('composite', sa.String(), nullable=True),
    sa.Column('filters', sa.Boolean(), nullable=True),
    sa.Column('key', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('locations', sa.JSON(), nullable=True),
    sa.Column('refreshing', sa.Boolean(), nullable=True),
    sa.Column('scanner', sa.String(), nullable=True),
    sa.Column('thumb', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('server',
    sa.Column('baseurl', sa.String(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('timeout', sa.Integer(), nullable=True),
    sa.Column('allowCameraUpload', sa.Boolean(), nullable=True),
    sa.Column('allowChannelAccess', sa.Boolean(), nullable=True),
    sa.Column('allowMediaDeletion', sa.Boolean(), nullable=True),
    sa.Column('allowSharing', sa.Boolean(), nullable=True),
    sa.Column('allowSync', sa.Boolean(), nullable=True),
    sa.Column('backgroundProcessing', sa.Boolean(), nullable=True),
    sa.Column('certificate', sa.Boolean(), nullable=True),
    sa.Column('companionProxy', sa.Boolean(), nullable=True),
    sa.Column('eventStream', sa.Boolean(), nullable=True),
    sa.Column('friendlyName', sa.String(), nullable=True),
    sa.Column('hubSearch', sa.Boolean(), nullable=True),
    sa.Column('machineIdentifier', sa.String(), nullable=True),
    sa.Column('multiuser', sa.Boolean(), nullable=True),
    sa.Column('myPlex', sa.Boolean(), nullable=True),
    sa.Column('myPlexMappingState', sa.String(), nullable=True),
    sa.Column('myPlexSigninState', sa.String(), nullable=True),
    sa.Column('myPlexSubscription', sa.Boolean(), nullable=True),
    sa.Column('myPlexUsername', sa.String(), nullable=True),
    sa.Column('photoAutoTag', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('platformVersion', sa.String(), nullable=True),
    sa.Column('pluginHost', sa.Boolean(), nullable=True),
    sa.Column('readOnlyLibraries', sa.Integer(), nullable=True),
    sa.Column('requestParametersInCookie', sa.String(), nullable=True),
    sa.Column('streamingBrainVersion', sa.String(), nullable=True),
    sa.Column('sync', sa.Boolean(), nullable=True),
    sa.Column('transcoderActiveVideoSessions', sa.Integer(), nullable=True),
    sa.Column('transcoderAudio', sa.Boolean(), nullable=True),
    sa.Column('transcoderLyrics', sa.Boolean(), nullable=True),
    sa.Column('transcoderPhoto', sa.Boolean(), nullable=True),
    sa.Column('transcoderSubtitles', sa.Boolean(), nullable=True),
    sa.Column('transcoderVideo', sa.Boolean(), nullable=True),
    sa.Column('updater', sa.Boolean(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('voiceSearch', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('server')
    op.drop_table('section')
    op.drop_table('movie')
    op.drop_table('library')
    # ### end Alembic commands ###
